site_name: Optum Documentation
site_url: https://example.com/
nav:
  - Home: index.md
  - Apache Airflow:
    - 'Setting': 'setting.md'
    - 'Configuration': 'configuration.md'
  - Hashicorp Vault:
    - 'Get Token': 'getToken.md'
    - 'Create Secrets': 'createSecrets.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette: 

    # Palette toggle for light mode
    - scheme: default
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



copyright: Copyright &copy; 2022 Optum
extra:
  generator: false